# Generated by Django 5.2.17 on 2026-10-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0812_delete_inaccessible_user_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="my_amazing_feature",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
